feat: selective function execution

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -202,6 +202,11 @@ function install_fnm_and_node_versions() {
 }
 
 function install_bun() {
+    if which bun >/dev/null; then
+        echo "bun is already installed."
+        return
+    fi
+
     echo "Installing bun..."
     curl -fsSL https://bun.sh/install | bash
 }
@@ -282,8 +287,22 @@ link_dotfiles() {
     cd "$current_dir"
 }
 
-# Run the above functions
 run() {
+    local function_name=$1
+    if declare -f "$function_name" >/dev/null; then
+        echo "Running $function_name..."
+        $function_name
+    else
+        echo "Error: Function '$function_name' not found."
+        exit 1
+    fi
+}
+
+# Check if a function name was passed as an argument
+if [ $# -gt 0 ]; then
+    run "$1"
+else
+    echo "No function specified. Running default functions..."
     show_variables
     install_command_line_tools
     install_oh_my_zsh
@@ -298,6 +317,4 @@ run() {
     setup_simple_bar
     clone_dotfiles_repo
     link_dotfiles
-}
-
-run
+fi
